# .github/workflows/ci.yml
name: Django CI

# Trigger the workflow on pushes to the main branch and pull requests
on:
  push:
    branches: ["main"] # Adjust branch name if needed
  pull_request:
    branches: ["main"] # Adjust branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      # Step 1: Check out the repository code
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9" # Match your project's Python version

      # Step 3: Install dependencies (including linters/test tools)
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 # Example linter
          # Add other testing tools here if needed (e.g., pytest)
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Lint with flake8 (Example check)
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # Step 5: Run Django Checks (Catches basic configuration issues)
      - name: Run Django Check
        run: python manage.py check

    # Step 6: Add Django Tests Here (Optional but recommended)
    # - name: Run Tests
    #   run: python manage.py test
